### ISSUE TITLE
batch_size of train and test

### ISSUE THREAD

**Issue by zllljf** [miao0913/SaCNN-CrowdCounting-Tencent_Youtu#15]
in your paper, you said you set the batch size as 1
but if i want to change the batch_size to 4, 
i find i change the parameter of batch_size in train.prototxt is not work, if i should change other parameters in other script?
thanks for your reply

**Comment by miao0913** [comment]
Hi, I did remember using batch size more than 1 needs some specific setting (maybe due to memory or image size ? ). I did not see you error report, but I can give you two alternative options: 
1. make sure the images in the same batch  are of the same size, which can be divided by 16 either W/H
2. use two GPU to simulate batch size =2 
I do not remember increasing batch size (or GPU number) gives out a big boost.

**Comment by zllljf** [comment]
thanks for reply
maybe i wasn't clear enough.
what i want to say is: i have croped the image into a size can dicided by 16, if train with 1 batch_size, the memory is used 1/4 ,  so i want to increase the batch_size of train.
where i can find batch_size parameter is in train.prototxt, but i chang this parameter 1 to 4, the memory is used 1/4 too.
so i think just change this parameter is not work, would like to tell me, where else do i need to change?

**Comment by miao0913** [comment]
Can I see the error report ?
